// web/with-react-nextjs/custom-phone-auth/src/components/AuthButton.tsx
"use client";

interface AuthButtonProps {
  isLoading: boolean;
  disabled?: boolean;
  onClick: () => void;
  loadingText?: string;
  children: React.ReactNode;
}

export function AuthButton({
  isLoading,
  disabled,
  onClick,
  loadingText = "Loading...",
  children,
}: AuthButtonProps) {
  return (
    <button
      disabled={disabled || isLoading}
      onClick={onClick}
      className="w-full px-4 py-2 bg-gray-800 text-white rounded-none hover:bg-gray-900 transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed font-medium">
      {isLoading ? loadingText : children}
    </button>
  );
}

// web/with-svelte-vite/src/components/auth/AuthButton.svelte
<script lang="ts">
  export let isLoading: boolean = false;
  export let disabled: boolean = false;
  export let onClick: () => void = () => {};
  export let loadingText: string = 'Loading...';
  export let variant: 'primary' | 'secondary' = 'primary';
</script>

<button
  on:click={onClick}
  disabled={disabled || isLoading}
  class="w-full px-4 py-2 font-medium rounded-none transition-colors disabled:cursor-not-allowed
    {variant === 'primary' 
      ? 'bg-gray-800 text-white hover:bg-gray-900 disabled:bg-gray-400' 
      : 'border border-gray-300 text-gray-700 hover:bg-gray-50 disabled:opacity-50'}"
>
  {#if isLoading}
    <span class="flex items-center justify-center gap-2">
      <span class="inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
      {loadingText}
    </span>
  {:else}
    <slot />
  {/if}
</button>
