// web/with-svelte-vite/src/components/auth/OTPInput.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  
  export let value: string = '';
  export let disabled: boolean = false;
  export let onChange: (value: string) => void = () => {};
  
  let inputs: HTMLInputElement[] = [];
  let values: string[] = ['', '', '', '', '', ''];
  
  onMount(() => {
    // Focus first input on mount
    inputs[0]?.focus();
  });
  
  function handleInput(index: number, event: Event) {
    const input = event.target as HTMLInputElement;
    const newValue = input.value;
    
    // Only allow digits
    if (!/^\d*$/.test(newValue)) {
      input.value = values[index];
      return;
    }
    
    values[index] = newValue;
    const fullValue = values.join('');
    value = fullValue;
    onChange(fullValue);
    
    // Auto-advance to next input
    if (newValue && index < 5) {
      inputs[index + 1]?.focus();
    }
  }
  
  function handleKeyDown(index: number, event: KeyboardEvent) {
    if (event.key === 'Backspace' && !values[index] && index > 0) {
      inputs[index - 1]?.focus();
    }
  }
  
  function handlePaste(event: ClipboardEvent) {
    event.preventDefault();
    const pastedData = event.clipboardData?.getData('text/plain') || '';
    const digits = pastedData.replace(/\D/g, '').slice(0, 6);
    
    if (digits) {
      values = [...digits.padEnd(6, '').split('')];
      const fullValue = values.join('');
      value = fullValue;
      onChange(fullValue);
      
      // Focus last filled input or last input
      const lastFilledIndex = Math.min(digits.length - 1, 5);
      inputs[lastFilledIndex]?.focus();
    }
  }
</script>

<div class="flex gap-2 justify-center" data-testid="otp-input">
  {#each values as _, index}
    <input
      bind:this={inputs[index]}
      type="text"
      inputmode="numeric"
      maxlength="1"
      {disabled}
      value={values[index]}
      on:input={(e) => handleInput(index, e)}
      on:keydown={(e) => handleKeyDown(index, e)}
      on:paste={handlePaste}
      class="w-12 h-12 text-center text-xl font-semibold border border-gray-300 rounded-none focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
      aria-label={`Digit ${index + 1} of verification code`}
      data-testid={`otp-input-${index}`}
    />
  {/each}
</div>

// web/with-react-nextjs/custom-phone-auth/src/components/OTPInput.tsx
import React, { useRef, KeyboardEvent, ClipboardEvent } from "react";

interface OTPInputProps {
  length?: number;
  value: string;
  onChange: (value: string) => void;
  onComplete?: (code: string) => void;
  label?: string;
  disabled?: boolean;
}

export const OTPInput: React.FC<OTPInputProps> = ({
  length = 6,
  value,
  onChange,
  onComplete,
  label = "Verification Code",
  disabled = false,
}) => {
  const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

  const otpArray = value.split("").concat(Array(length).fill("")).slice(0, length);

  const focusInput = (index: number) => {
    inputRefs.current[index]?.focus();
  };

  const handleChange = (index: number, inputValue: string) => {
    if (!/^\d*$/.test(inputValue)) return;

    const newValue = otpArray.map((char, i) => (i === index ? inputValue.slice(-1) : char)).join("");

    onChange(newValue);

    if (inputValue && index < length - 1) {
      focusInput(index + 1);
    }

    if (newValue.length === length && onComplete) {
      onComplete(newValue);
    }
  };

  const handleKeyDown = (index: number, e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !otpArray[index] && index > 0) {
      focusInput(index - 1);
    }
  };

  const handlePaste = (e: ClipboardEvent<HTMLInputElement>) => {
    e.preventDefault();
    const pastedData = e.clipboardData.getData("text").slice(0, length);
    if (!/^\d*$/.test(pastedData)) return;

    const newValue = pastedData.padEnd(length, "").slice(0, length);
    onChange(newValue);

    const focusIndex = Math.min(pastedData.length, length - 1);
    focusInput(focusIndex);

    if (newValue.length === length && onComplete) {
      onComplete(newValue);
    }
  };

  return (
    <div className="w-full">
      <label className="block text-sm font-medium text-gray-700 mb-2">{label}</label>
      <div className="flex gap-2">
        {otpArray.map((digit, index) => (
          <input
            key={index}
            ref={(el) => {
              inputRefs.current[index] = el;
            }}
            type="text"
            inputMode="numeric"
            maxLength={1}
            value={digit}
            onChange={(e) => handleChange(index, e.target.value)}
            onKeyDown={(e) => handleKeyDown(index, e)}
            onPaste={handlePaste}
            disabled={disabled}
            data-testid={`auth-otp-input-${index}`}
            className="w-12 h-12 text-center border border-gray-300 rounded-xs focus:ring-2 focus:ring-gray-500 focus:border-gray-500 text-lg disabled:bg-gray-100 disabled:cursor-not-allowed"
            autoComplete="off"
          />
        ))}
      </div>
    </div>
  );
};
