// web/with-svelte-vite/src/components/auth/EmailAuthTab.svelte
<script lang="ts">
  import { authModal, signUpOrLoginWithEmail, verifyAccount, waitForLogin, waitForWalletCreation } from '@/stores/paraAuth';
  import AuthButton from './AuthButton.svelte';
  import OTPInput from './OTPInput.svelte';
  
  let popupWindow: Window | null = null;
  
  $: ({ email, verificationCode, step, isLoading, error } = $authModal);
  
  function openPopup(url: string, name: string) {
    popupWindow?.close();
    popupWindow = window.open(url, name, 'popup=true');
  }
  
  async function handleEmailSubmit() {
    if (!email) return;
    
    try {
      const authState = await signUpOrLoginWithEmail(email);
      
      if (authState.stage === 'login' && 'passkeyUrl' in authState && authState.passkeyUrl) {
        openPopup(authState.passkeyUrl, 'loginPopup');
        await waitForLogin(() => popupWindow?.closed ?? true);
      }
    } catch {
      // Error handled in store
    }
  }
  
  async function handleVerification() {
    if (!verificationCode) return;
    
    try {
      const authState = await verifyAccount(verificationCode);
      
      if ('passkeyUrl' in authState && authState.passkeyUrl) {
        openPopup(authState.passkeyUrl, 'signUpPopup');
        await waitForWalletCreation(() => Boolean(popupWindow?.closed));
      }
    } catch {
      // Error handled in store
    }
  }
  
  function handleEmailChange(e: Event) {
    const target = e.target as HTMLInputElement;
    authModal.update(state => ({ ...state, email: target.value }));
  }
  
  function handleOTPChange(value: string) {
    authModal.update(state => ({ ...state, verificationCode: value }));
  }
</script>

<div class="space-y-4">
  {#if step === 'select' || step === 'email'}
    <div>
      <label for="email" class="block text-sm font-medium text-gray-700 mb-2">
        Email Address
      </label>
      <input
        id="email"
        type="email"
        value={email}
        on:input={handleEmailChange}
        disabled={isLoading}
        placeholder="you@example.com"
        class="w-full px-3 py-2 border border-gray-300 rounded-none focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
      />
    </div>
    
    <AuthButton
      {isLoading}
      disabled={!email}
      onClick={handleEmailSubmit}
    >
      Continue with Email
    </AuthButton>
  {/if}
  
  {#if step === 'verify'}
    <div class="text-center space-y-4">
      <p class="text-sm text-gray-600">
        We sent a verification code to {email}
      </p>
      
      <OTPInput
        value={verificationCode}
        onChange={handleOTPChange}
        disabled={isLoading}
      />
      
      <AuthButton
        {isLoading}
        disabled={!verificationCode || verificationCode.length !== 6}
        onClick={handleVerification}
        loadingText="Verifying..."
      >
        Verify & Create Wallet
      </AuthButton>
    </div>
  {/if}
  
  {#if step === 'login'}
    <div class="text-center py-8">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto mb-4"></div>
      <p class="text-gray-600">Completing login...</p>
    </div>
  {/if}
  
  {#if error}
    <div class="p-3 bg-red-50 border border-red-200 text-red-700 text-sm rounded-none">
      {error}
    </div>
  {/if}
</div>

// web/with-vue-vite/src/components/auth/EmailAuthTab.vue
<template>
  <div class="space-y-4">
    <template v-if="state.step === 'select' || state.step === 'email'">
      <div>
        <label for="email" class="block text-sm font-medium text-gray-700 mb-2">
          Email Address
        </label>
        <input
          id="email"
          type="email"
          v-model="state.email"
          :disabled="state.isLoading"
          placeholder="you@example.com"
          class="w-full px-3 py-2 border border-gray-300 rounded-none focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
        />
      </div>
      
      <AuthButton
        :is-loading="state.isLoading"
        :disabled="!state.email"
        @click="handleEmailSubmit"
      >
        Continue with Email
      </AuthButton>
    </template>
    
    <template v-else-if="state.step === 'verify'">
      <div class="text-center space-y-4">
        <p class="text-sm text-gray-600">
          We sent a verification code to {{ state.email }}
        </p>
        
        <OTPInput
          v-model="state.verificationCode"
          :disabled="state.isLoading"
        />
        
        <AuthButton
          :is-loading="state.isLoading"
          :disabled="!state.verificationCode || state.verificationCode.length !== 6"
          @click="handleVerification"
          loading-text="Verifying..."
        >
          Verify & Create Wallet
        </AuthButton>
      </div>
    </template>
    
    <template v-else-if="state.step === 'login'">
      <div class="text-center py-8">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto mb-4"></div>
        <p class="text-gray-600">Completing login...</p>
      </div>
    </template>
    
    <div v-if="state.error" class="p-3 bg-gray-100 border border-gray-300 text-gray-700 text-sm rounded-none">
      {{ state.error }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useParaAuth } from '@/composables/useParaAuth';
import AuthButton from './AuthButton.vue';
import OTPInput from './OTPInput.vue';

const { state, signUpOrLoginWithEmail, verifyAccount, waitForLogin, waitForWalletCreation } = useParaAuth();

let popupWindow = ref<Window | null>(null);

function openPopup(url: string, name: string) {
  popupWindow.value?.close();
  popupWindow.value = window.open(url, name, 'popup=true');
}

async function handleEmailSubmit() {
  if (!state.email) return;
  
  try {
    const authState = await signUpOrLoginWithEmail(state.email);
    
    if (authState.stage === 'login' && 'passkeyUrl' in authState && authState.passkeyUrl) {
      openPopup(authState.passkeyUrl, 'loginPopup');
      await waitForLogin(() => popupWindow.value?.closed ?? true);
    }
  } catch {
    // Error handled in composable
  }
}

async function handleVerification() {
  if (!state.verificationCode) return;
  
  try {
    const authState = await verifyAccount(state.verificationCode);
    
    if ('passkeyUrl' in authState && authState.passkeyUrl) {
      openPopup(authState.passkeyUrl, 'signUpPopup');
      await waitForWalletCreation(() => Boolean(popupWindow.value?.closed));
    }
  } catch {
    // Error handled in composable
  }
}
</script>
