// web/with-react-nextjs/custom-phone-auth/src/components/ui/AccountMenu.tsx
import { useId, type KeyboardEvent, type MouseEvent } from "react";
import { Button } from "@/components/ui/Button";
import { CopyButton } from "@/components/ui/CopyButton";
import { Icon } from "@/components/ui/Icon";
import type { CopyStatus } from "@/lib/useCopyToClipboard";

interface AccountMenuProps {
  isOpen: boolean;
  onClose: () => void;
  address: string;
  title?: string;
  connectionLabel?: string;
  addressCopyStatus?: CopyStatus;
  onCopyAddress?: () => void;
  explorerHref?: string;
  explorerLabel?: string;
  onDisconnect: () => void;
  isDisconnecting?: boolean;
  disconnectLabel?: string;
  disconnectTestId?: string;
}

export function AccountMenu({
  isOpen,
  onClose,
  address,
  title = "Account",
  connectionLabel = "Connected with Para",
  addressCopyStatus = "idle",
  onCopyAddress,
  explorerHref,
  explorerLabel = "View on explorer",
  onDisconnect,
  isDisconnecting = false,
  disconnectLabel = "Disconnect",
  disconnectTestId,
}: AccountMenuProps) {
  const titleId = useId();

  if (!isOpen) {
    return null;
  }

  const closeOnBackdrop = (event: MouseEvent<HTMLDivElement>) => {
    if (event.target === event.currentTarget) {
      onClose();
    }
  };

  const closeOnEscape = (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key === "Escape") {
      onClose();
    }
  };

  return (
    <div className="fixed inset-0 z-20" onClick={closeOnBackdrop} onKeyDown={closeOnEscape}>
      <div
        className="mx-auto flex max-w-sheet justify-end px-gutter pt-[calc(var(--spacing-header)+8px)] md:px-sheet-x"
        onClick={closeOnBackdrop}>
        <section
          role="dialog"
          aria-labelledby={titleId}
          className="grid w-90 max-w-full gap-5 border border-border-strong bg-background p-6 text-foreground shadow-menu">
          <header className="flex items-center justify-between gap-4">
            <h2 id={titleId} className="text-heading tracking-snug">
              {title}
            </h2>
            <Button variant="ghost" size="icon" autoFocus onClick={onClose} icon={<Icon name="x" className="size-icon-md" />}>
              Close
            </Button>
          </header>
          <div className="grid gap-2">
            <span className="font-mono text-mono-label text-muted uppercase">{connectionLabel}</span>
            <code className="border border-border bg-surface p-3 font-mono text-code [overflow-wrap:anywhere]">{address}</code>
          </div>
          {(onCopyAddress || explorerHref) && (
            <div className="flex flex-wrap gap-2">
              {onCopyAddress && (
                <CopyButton
                  size="md"
                  label="Copy address"
                  copiedMessage="Address copied"
                  status={addressCopyStatus}
                  onCopy={onCopyAddress}
                />
              )}
              {explorerHref && (
                <a
                  href={explorerHref}
                  target="_blank"
                  rel="noreferrer"
                  className="focus-ring state-layer inline-flex min-h-control-md items-center gap-2 px-control-x text-label tracking-ui text-foreground">
                  <Icon name="arrow-up-right" className="size-icon-md" />
                  {explorerLabel}
                </a>
              )}
            </div>
          )}
          <div className="border-t border-border pt-4">
            <Button
              variant="destructive"
              isLoading={isDisconnecting}
              onClick={onDisconnect}
              data-testid={disconnectTestId}
              icon={<Icon name="sign-out" className="size-icon-md" />}>
              {disconnectLabel}
            </Button>
          </div>
        </section>
      </div>
    </div>
  );
}

// web/with-vue-vite/src/components/ui/AccountMenu.vue
<script setup lang="ts">
import { nextTick, ref, useId, watch } from "vue";
import Button from "@/components/ui/Button.vue";
import CopyButton from "@/components/ui/CopyButton.vue";
import Icon from "@/components/ui/Icon.vue";
import type { CopyStatus } from "@/lib/useCopyToClipboard";

const props = withDefaults(
  defineProps<{
    isOpen: boolean;
    onClose: () => void;
    address: string;
    title?: string;
    connectionLabel?: string;
    addressCopyStatus?: CopyStatus;
    onCopyAddress?: () => void;
    explorerHref?: string;
    explorerLabel?: string;
    onDisconnect: () => void;
    isDisconnecting?: boolean;
    disconnectLabel?: string;
    disconnectTestId?: string;
  }>(),
  {
    title: "Account",
    connectionLabel: "Connected with Para",
    addressCopyStatus: "idle",
    onCopyAddress: undefined,
    explorerHref: undefined,
    explorerLabel: "View on explorer",
    isDisconnecting: false,
    disconnectLabel: "Disconnect",
    disconnectTestId: undefined,
  }
);

const titleId = useId();
const closeButton = ref<InstanceType<typeof Button> | null>(null);

watch(
  () => props.isOpen,
  async (isOpen) => {
    if (isOpen) {
      await nextTick();
      closeButton.value?.focus();
    }
  },
  { immediate: true }
);

function closeOnBackdrop(event: MouseEvent) {
  if (event.target === event.currentTarget) {
    props.onClose();
  }
}

function closeOnEscape(event: KeyboardEvent) {
  if (event.key === "Escape") {
    props.onClose();
  }
}
</script>

<template>
  <div
    v-if="isOpen"
    class="fixed inset-0 z-20"
    @click="closeOnBackdrop"
    @keydown="closeOnEscape">
    <div
      class="mx-auto flex max-w-sheet justify-end px-gutter pt-[calc(var(--spacing-header)+8px)] md:px-sheet-x"
      @click="closeOnBackdrop">
      <section
        role="dialog"
        :aria-labelledby="titleId"
        class="grid w-90 max-w-full gap-5 border border-border-strong bg-background p-6 text-foreground shadow-menu">
        <header class="flex items-center justify-between gap-4">
          <h2
            :id="titleId"
            class="text-heading tracking-snug">
            {{ title }}
          </h2>
          <Button
            ref="closeButton"
            variant="ghost"
            size="icon"
            @click="onClose">
            <template #icon>
              <Icon
                name="x"
                class-name="size-icon-md" />
            </template>
            Close
          </Button>
        </header>
        <div class="grid gap-2">
          <span class="font-mono text-mono-label text-muted uppercase">{{ connectionLabel }}</span>
          <code class="border border-border bg-surface p-3 font-mono text-code [overflow-wrap:anywhere]">{{ address }}</code>
        </div>
        <div
          v-if="onCopyAddress || explorerHref"
          class="flex flex-wrap gap-2">
          <CopyButton
            v-if="onCopyAddress"
            size="md"
            label="Copy address"
            copied-message="Address copied"
            :status="addressCopyStatus"
            :on-copy="onCopyAddress" />
          <a
            v-if="explorerHref"
            :href="explorerHref"
            target="_blank"
            rel="noreferrer"
            class="focus-ring state-layer inline-flex min-h-control-md items-center gap-2 px-control-x text-label tracking-ui text-foreground">
            <Icon
              name="arrow-up-right"
              class-name="size-icon-md" />
            {{ explorerLabel }}
          </a>
        </div>
        <div class="border-t border-border pt-4">
          <Button
            variant="destructive"
            :is-loading="isDisconnecting"
            :data-testid="disconnectTestId"
            @click="onDisconnect">
            <template #icon>
              <Icon
                name="sign-out"
                class-name="size-icon-md" />
            </template>
            {{ disconnectLabel }}
          </Button>
        </div>
      </section>
    </div>
  </div>
</template>
