// packages/react-component-library/src/components/base/alert.tsx
import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';

import { cn } from '@/lib/utils';

const alertVariants = cva(
  'para:relative para:w-full para:rounded-lg para:border para:px-4 para:py-3 para:text-sm para:grid para:has-[>svg]:grid-cols-[calc(var(--spacing)*4)_1fr] para:grid-cols-[0_1fr] para:has-[>svg]:gap-x-3 para:gap-y-0.5 para:items-start para:[&>svg]:size-4 para:[&>svg]:translate-y-0.5 para:[&>svg]:text-current',
  {
    variants: {
      variant: {
        default: 'para:bg-background para:text-foreground',
        destructive:
          'para:text-destructive-foreground para:[&>svg]:text-current para:*:data-[slot=alert-description]:text-destructive-foreground/80',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  },
);

function Alert({ className, variant, ...props }: React.ComponentProps<'div'> & VariantProps<typeof alertVariants>) {
  return <div data-slot="alert" role="alert" className={cn(alertVariants({ variant }), className)} {...props} />;
}

function AlertTitle({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="alert-title"
      className={cn('para:col-start-2 para:line-clamp-1 para:min-h-4 para:font-medium para:tracking-tight', className)}
      {...props}
    />
  );
}

function AlertDescription({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      data-slot="alert-description"
      className={cn(
        'para:text-muted-foreground para:col-start-2 para:grid para:justify-items-start para:gap-1 para:text-sm para:[&_p]:leading-relaxed',
        className,
      )}
      {...props}
    />
  );
}

export { Alert, AlertTitle, AlertDescription };

// web/with-vue-vite/src/components/ui/Alert.vue
<script lang="ts">
export type AlertVariant = "info" | "success" | "warning" | "destructive";
</script>

<script setup lang="ts">
import { useSlots } from "vue";
import Icon, { type IconName } from "@/components/ui/Icon.vue";
import { cx } from "@/lib/classNames";

withDefaults(defineProps<{ variant?: AlertVariant; title?: string; className?: string; testId?: string }>(), {
  variant: "info",
  title: undefined,
  className: undefined,
  testId: undefined,
});

const slots = useSlots();

const EDGE_CLASSES: Record<AlertVariant, string> = {
  info: "border-l-foreground",
  success: "border-l-success",
  warning: "border-l-warning",
  destructive: "border-l-destructive",
};

const ICON_CLASSES: Record<AlertVariant, string> = {
  info: "text-foreground",
  success: "text-success",
  warning: "text-warning",
  destructive: "text-destructive",
};

const ICON_NAMES: Record<AlertVariant, IconName> = {
  info: "info",
  success: "check",
  warning: "warning",
  destructive: "warning",
};
</script>

<template>
  <div
    :role="variant === 'destructive' ? 'alert' : 'status'"
    :data-testid="testId"
    :class="cx('flex items-start gap-3 border border-l-2 border-border bg-surface p-4 text-foreground', EDGE_CLASSES[variant], className)">
    <Icon
      :name="ICON_NAMES[variant]"
      :class-name="cx('mt-0.5 size-icon-md', ICON_CLASSES[variant])" />
    <div class="grid min-w-0 gap-1">
      <p
        v-if="title"
        class="text-body font-medium">
        {{ title }}
      </p>
      <div
        v-if="slots.default"
        class="text-caption break-words text-muted">
        <slot />
      </div>
    </div>
  </div>
</template>
