// packages/react-component-library/src/components/base/badge.tsx
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';

import { cn } from '@/lib/utils';

const badgeVariants = cva(
  'para:inline-flex para:items-center para:justify-center para:rounded-sm para:border para:px-2 para:py-0.5 para:text-xs para:font-medium para:w-fit para:whitespace-nowrap para:shrink-0 para:[&>svg]:size-3 para:gap-1 para:[&>svg]:pointer-events-none para:focus-visible:border-ring para:focus-visible:ring-ring/50 para:focus-visible:ring-[3px] para:aria-invalid:ring-destructive/20 para:dark:aria-invalid:ring-destructive/40 para:aria-invalid:border-destructive para:transition-[color,box-shadow] para:overflow-hidden',
  {
    variants: {
      variant: {
        default: 'para:border-transparent para:bg-primary para:text-primary-foreground para:[a&]:hover:bg-primary/90',
        secondary:
          'para:border-transparent para:bg-secondary para:text-secondary-foreground para:[a&]:hover:bg-secondary/90',
        destructive:
          'para:border-transparent para:bg-destructive para:text-white para:[a&]:hover:bg-destructive/90 para:focus-visible:ring-destructive/20 para:dark:focus-visible:ring-destructive/40',
        outline: 'para:text-foreground para:[a&]:hover:bg-accent para:[a&]:hover:text-accent-foreground',
        neutral: 'para:bg-foreground para:text-primary-foreground para:hover:bg-foreground/90',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  },
);

function Badge({
  className,
  variant,
  asChild = false,
  ...props
}: React.ComponentProps<'span'> & VariantProps<typeof badgeVariants> & { asChild?: boolean }) {
  const Comp = asChild ? Slot : 'span';

  return <Comp data-slot="badge" className={cn(badgeVariants({ variant }), className)} {...props} />;
}

export { Badge, badgeVariants };

// web/with-vue-vite/src/components/ui/Badge.vue
<script lang="ts">
export type BadgeVariant = "solid" | "outline" | "success" | "accent";
</script>

<script setup lang="ts">
import { cx } from "@/lib/classNames";

withDefaults(defineProps<{ variant?: BadgeVariant; className?: string }>(), {
  variant: "outline",
  className: undefined,
});

const VARIANT_CLASSES: Record<BadgeVariant, string> = {
  solid: "border-transparent bg-primary text-on-primary",
  outline: "border-border-strong bg-transparent text-foreground",
  success: "border-border bg-surface text-foreground",
  accent: "border-border bg-surface text-foreground",
};

const DOT_CLASSES: Partial<Record<BadgeVariant, string>> = {
  success: "bg-success",
  accent: "bg-accent",
};
</script>

<template>
  <span
    :class="cx('inline-flex items-center gap-1 border px-2 py-0.5 text-label whitespace-nowrap', VARIANT_CLASSES[variant], className)">
    <span
      v-if="DOT_CLASSES[variant]"
      aria-hidden="true"
      :class="cx('size-1.5 flex-none rounded-full', DOT_CLASSES[variant])" />
    <slot />
  </span>
</template>
