// web/with-react-nextjs/custom-combined-auth/src/components/ui/PhoneForm.tsx
import type { CountryCodeOption } from "@/types/auth";

interface PhoneFormProps {
  countryCode: string;
  phoneNumber: string;
  onCountryCodeChange: (code: string) => void;
  onPhoneNumberChange: (phone: string) => void;
  onSubmit: () => void;
  isPending: boolean;
  disabled?: boolean;
  countryCodes: readonly CountryCodeOption[];
}

export function PhoneForm({
  countryCode,
  phoneNumber,
  onCountryCodeChange,
  onPhoneNumberChange,
  onSubmit,
  isPending,
  disabled,
  countryCodes,
}: PhoneFormProps) {
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit();
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label htmlFor="phone" className="mb-1.5 block text-sm font-medium text-card-foreground">
          Phone number
        </label>
        <div className="grid grid-cols-[minmax(7rem,9rem)_minmax(0,1fr)] gap-2">
          <select
            id="countryCode"
            value={countryCode}
            onChange={(e) => onCountryCodeChange(e.target.value)}
            disabled={disabled || isPending}
            className="min-h-11 rounded-lg border border-border bg-card px-3 text-sm text-card-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15 disabled:cursor-not-allowed disabled:bg-muted">
            {countryCodes.map(({ code, label }) => (
              <option key={code} value={code}>
                {label}
              </option>
            ))}
          </select>
          <input
            id="phone"
            type="tel"
            value={phoneNumber}
            onChange={(e) => onPhoneNumberChange(e.target.value)}
            placeholder="(555) 123-4567"
            disabled={disabled || isPending}
            className="min-h-11 min-w-0 rounded-lg border border-border bg-card px-3 text-sm text-card-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15 disabled:cursor-not-allowed disabled:bg-muted"
            required
          />
        </div>
      </div>
      <button
        type="submit"
        disabled={isPending || !phoneNumber || disabled}
        className="btn-primary min-h-11 w-full px-4 text-sm">
        {isPending ? "Loading..." : "Continue with Phone"}
      </button>
    </form>
  );
}

// web/with-vue-vite/src/components/ui/PhoneForm.vue
<script setup lang="ts">
import { ref } from "vue";
import { usePhoneAuth } from "@/composables/auth/usePhoneAuth";
import { COUNTRY_CODES } from "@/constants/auth";

defineProps<{
  isPending: boolean;
}>();

const { submit } = usePhoneAuth();
const countryCode = ref("+1");
const phoneNumber = ref("");

async function handleSubmit(e: Event) {
  e.preventDefault();
  if (!phoneNumber.value.trim()) return;
  await submit(phoneNumber.value.trim(), countryCode.value);
}
</script>

<template>
  <form @submit="handleSubmit" class="space-y-4">
    <div>
      <label for="phone" class="block text-sm font-medium text-gray-700 mb-1">
        Phone Number
      </label>
      <div class="flex gap-2">
        <select
          v-model="countryCode"
          :disabled="isPending"
          class="px-2 py-2 border border-gray-300 text-sm focus:outline-none focus:ring-1 focus:ring-gray-900 focus:border-gray-900 disabled:bg-gray-100 disabled:cursor-not-allowed"
        >
          <option v-for="{ code, label } in COUNTRY_CODES" :key="code" :value="code">
            {{ label }}
          </option>
        </select>
        <input
          id="phone"
          v-model="phoneNumber"
          type="tel"
          placeholder="123-456-7890"
          :disabled="isPending"
          required
          class="flex-1 px-3 py-2 border border-gray-300 text-sm focus:outline-none focus:ring-1 focus:ring-gray-900 focus:border-gray-900 disabled:bg-gray-100 disabled:cursor-not-allowed"
        />
      </div>
    </div>

    <button
      type="submit"
      :disabled="!phoneNumber.trim() || isPending"
      class="w-full py-2 px-4 bg-gray-900 text-white text-sm font-medium hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
    >
      {{ isPending ? "Signing in..." : "Continue with Phone" }}
    </button>
  </form>
</template>
