// web/with-svelte-vite/src/components/sign-in/CombinedSignInContainer.svelte
<script lang="ts">
  import Alert from "@/components/ui/Alert.svelte";
  import Button from "@/components/ui/Button.svelte";
  import Icon from "@/components/ui/Icon.svelte";
  import OAuthProviderList from "@/components/ui/OAuthProviderList.svelte";
  import SegmentedControl from "@/components/ui/SegmentedControl.svelte";
  import SelectField from "@/components/ui/SelectField.svelte";
  import SignInPanel from "@/components/ui/SignInPanel.svelte";
  import StatusHint from "@/components/ui/StatusHint.svelte";
  import TextField from "@/components/ui/TextField.svelte";
  import VerificationFrame from "@/components/ui/VerificationFrame.svelte";
  import type { CombinedAuth } from "@/hooks/useCombinedAuth.svelte.js";
  import { formatErrorMessage } from "@/lib/format";
  import { SIGN_IN_DESCRIPTION, getVerifyDescription, getVerifyTitle } from "@/lib/signInCopy";
  import { AUTH_TABS, COUNTRY_CODES, OAUTH_PROVIDERS } from "@/lib/signInOptions";

  interface Props {
    auth: CombinedAuth;
    network: string;
  }

  let { auth, network }: Props = $props();

  const email = $derived(auth.email);
  const phone = $derived(auth.phone);
  const oauth = $derived(auth.oauth);
  const errorMessage = $derived(formatErrorMessage(auth.error));
  const destination = $derived(
    auth.activeTab === "email" ? email.email : `${phone.countryCode} ${phone.phoneNumber}`
  );
  const hasFrame = $derived(Boolean(auth.verifyUrl));
  const hasPasskey = $derived(Boolean(auth.passkeyUrl));

  function submitEmail(event: SubmitEvent) {
    event.preventDefault();
    void email.submit();
  }

  function submitPhone(event: SubmitEvent) {
    event.preventDefault();
    void phone.submit();
  }
</script>

{#snippet errorAlert()}
  {#if errorMessage}
    <Alert variant="destructive" title="Sign in failed">{errorMessage}</Alert>
  {/if}
{/snippet}

{#if auth.activeTab !== "social" && auth.step === "verify" && (hasFrame || hasPasskey)}
  <SignInPanel
    title={getVerifyTitle(hasFrame, hasPasskey)}
    description={getVerifyDescription(destination, hasFrame, hasPasskey)}
    {network}>
    {@render errorAlert()}
    {#if auth.verifyUrl}
      <VerificationFrame url={auth.verifyUrl} />
    {/if}
    {#if hasPasskey}
      <Button size="lg" fullWidth onclick={auth.openPasskeyWindow}>
        {#snippet icon()}
          <Icon name="fingerprint-simple" className="size-icon-md" />
        {/snippet}
        Open Passkey Verification
      </Button>
      <StatusHint>Waiting for the passkey window to finish.</StatusHint>
    {/if}
    <Button variant="outline" size="lg" fullWidth onclick={auth.cancel}>Cancel</Button>
  </SignInPanel>
{:else}
  <SignInPanel description={SIGN_IN_DESCRIPTION} {network}>
    <SegmentedControl
      label="Sign in with"
      options={AUTH_TABS}
      value={auth.activeTab}
      onChange={auth.setActiveTab}
      disabled={auth.isPending} />
    {@render errorAlert()}

    {#if auth.activeTab === "email"}
      <form onsubmit={submitEmail} class="grid gap-4">
        <TextField
          label="Email address"
          type="email"
          autocomplete="email"
          placeholder="you@example.com"
          value={email.email}
          oninput={(event) => email.setEmail(event.currentTarget.value)}
          disabled={email.isPending}
          required
          data-testid="email-input" />
        <Button
          type="submit"
          size="lg"
          fullWidth
          isLoading={email.isPending}
          disabled={!email.email.trim()}
          data-testid="continue-email-button">
          Continue with Email
        </Button>
      </form>
    {:else if auth.activeTab === "phone"}
      <form onsubmit={submitPhone} class="grid gap-4">
        <SelectField
          label="Country"
          options={COUNTRY_CODES}
          value={phone.countryCode}
          onchange={(event) => phone.setCountryCode(event.currentTarget.value)}
          disabled={phone.isPending} />
        <TextField
          label="Phone number"
          type="tel"
          autocomplete="tel-national"
          placeholder="123-456-7890"
          prefix={phone.countryCode}
          value={phone.phoneNumber}
          oninput={(event) => phone.setPhoneNumber(event.currentTarget.value)}
          disabled={phone.isPending}
          required
          data-testid="phone-input" />
        <Button
          type="submit"
          size="lg"
          fullWidth
          isLoading={phone.isPending}
          disabled={!phone.phoneNumber.trim()}
          data-testid="continue-phone-button">
          Continue with Phone
        </Button>
      </form>
    {:else}
      <OAuthProviderList
        providers={OAUTH_PROVIDERS}
        onSelect={oauth.authenticate}
        activeId={oauth.activeProvider}
        disabled={oauth.isPending}
        layout="grid"
        labelPrefix="" />
      {#if oauth.isPending}
        <Alert title="Continue in the pop-up">Complete authentication in the popup window.</Alert>
        <Button variant="outline" size="lg" fullWidth onclick={oauth.cancel}>Cancel</Button>
      {/if}
    {/if}
  </SignInPanel>
{/if}

// web/with-react-nextjs/custom-combined-auth/src/components/sign-in/CombinedSignInContainer.tsx
import type { FormEvent } from "react";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { Icon } from "@/components/ui/Icon";
import { OAuthProviderList } from "@/components/ui/OAuthProviderList";
import { SegmentedControl } from "@/components/ui/SegmentedControl";
import { SelectField } from "@/components/ui/SelectField";
import { SignInPanel } from "@/components/ui/SignInPanel";
import { StatusHint } from "@/components/ui/StatusHint";
import { TextField } from "@/components/ui/TextField";
import { VerificationFrame } from "@/components/ui/VerificationFrame";
import type { UseCombinedAuthReturn } from "@/hooks/useCombinedAuth";
import { describeSignInError, getVerifyDescription, getVerifyTitle } from "@/lib/signInCopy";
import { AUTH_TABS, COUNTRY_CODES, OAUTH_PROVIDERS, getOAuthProviderLabel } from "@/lib/signInOptions";

interface CombinedSignInContainerProps {
  auth: UseCombinedAuthReturn;
  network: string;
}

const SIGN_IN_DESCRIPTION = "Use your email, phone number, or a social account.";

export function CombinedSignInContainer({ auth, network }: CombinedSignInContainerProps) {
  const { email, phone, oauth } = auth;
  const error = describeSignInError(auth.error);
  const errorAlert = error && (
    <Alert variant="destructive" title={error.title}>
      {error.message}
    </Alert>
  );

  if (auth.activeTab !== "social" && auth.step === "verify" && (auth.verifyUrl || auth.passkeyUrl)) {
    const hasFrame = Boolean(auth.verifyUrl);
    const hasPasskey = Boolean(auth.passkeyUrl);
    const destination = auth.activeTab === "email" ? email.email : `${phone.countryCode} ${phone.phoneNumber}`;

    return (
      <SignInPanel
        title={getVerifyTitle(auth.activeTab, hasFrame, hasPasskey)}
        description={getVerifyDescription(destination, hasFrame, hasPasskey)}
        network={network}>
        {errorAlert}
        {auth.verifyUrl && <VerificationFrame url={auth.verifyUrl} />}
        {hasPasskey && (
          <>
            <Button
              size="lg"
              fullWidth
              onClick={auth.openPasskeyWindow}
              icon={<Icon name="fingerprint-simple" className="size-icon-md" />}>
              Open Passkey Verification
            </Button>
            <StatusHint>Waiting for the passkey window to finish.</StatusHint>
          </>
        )}
        <Button variant="outline" size="lg" fullWidth onClick={auth.cancel}>
          Cancel
        </Button>
      </SignInPanel>
    );
  }

  const oauthProviderLabel = oauth.isPending ? getOAuthProviderLabel(oauth.activeProvider) : null;

  const submitEmail = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    email.submit();
  };

  const submitPhone = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    phone.submit();
  };

  return (
    <SignInPanel
      description={
        oauthProviderLabel ? `Finish signing in with ${oauthProviderLabel} in the pop-up window.` : SIGN_IN_DESCRIPTION
      }
      network={network}>
      <SegmentedControl
        label="Sign in with"
        options={AUTH_TABS}
        value={auth.activeTab}
        onChange={auth.setActiveTab}
        disabled={auth.isPending}
      />
      {errorAlert}

      {auth.activeTab === "email" && (
        <form onSubmit={submitEmail} className="grid gap-4">
          <TextField
            label="Email"
            type="email"
            autoComplete="email"
            placeholder="you@example.com"
            value={email.email}
            onChange={(event) => email.setEmail(event.target.value)}
            disabled={email.isPending}
            required
          />
          <Button type="submit" size="lg" fullWidth isLoading={email.isPending} disabled={!email.email}>
            Continue
          </Button>
        </form>
      )}

      {auth.activeTab === "phone" && (
        <form onSubmit={submitPhone} className="grid gap-4">
          <SelectField
            label="Country"
            options={COUNTRY_CODES}
            value={phone.countryCode}
            onChange={(event) => phone.setCountryCode(event.target.value)}
            disabled={phone.isPending}
          />
          <TextField
            label="Phone number"
            type="tel"
            autoComplete="tel-national"
            placeholder="(555) 123-4567"
            prefix={phone.countryCode}
            value={phone.phoneNumber}
            onChange={(event) => phone.setPhoneNumber(event.target.value)}
            disabled={phone.isPending}
            required
          />
          <Button type="submit" size="lg" fullWidth isLoading={phone.isPending} disabled={!phone.phoneNumber}>
            Continue
          </Button>
        </form>
      )}

      {auth.activeTab === "social" && (
        <>
          <OAuthProviderList
            providers={OAUTH_PROVIDERS}
            onSelect={oauth.authenticate}
            activeId={oauth.isPending ? oauth.activeProvider : null}
            disabled={oauth.isPending}
          />
          {oauth.isPending && (
            <Button variant="outline" size="lg" fullWidth onClick={oauth.cancel}>
              Cancel
            </Button>
          )}
        </>
      )}
    </SignInPanel>
  );
}
