// web/with-svelte-vite/src/components/ui/StatusAlert.svelte
<script lang="ts">
  export let show: boolean = false;
  export let type: "info" | "error" | "success" = "info";
  export let message: string = "";

  $: alertClasses = {
    info: "bg-blue-50 text-blue-800 border-blue-200",
    error: "bg-red-50 text-red-800 border-red-200",
    success: "bg-green-50 text-green-800 border-green-200",
  }[type];
</script>

{#if show}
  <div class="mb-6 rounded-none border p-4 {alertClasses}">
    <p class="text-sm font-medium">{message}</p>
  </div>
{/if}

// specialized/with-electronjs/src/components/ui/StatusAlert.tsx
interface StatusAlertProps {
  show: boolean;
  type: 'info' | 'error' | 'success';
  message: string;
}

export function StatusAlert({ show, type, message }: StatusAlertProps) {
  if (!show) return null;

  const styles = {
    info: 'bg-blue-50 border-blue-200 text-blue-800',
    error: 'bg-red-50 border-red-200 text-red-800',
    success: 'bg-green-50 border-green-200 text-green-800',
  };

  return (
    <div className={`rounded-none border p-4 mb-6 ${styles[type]}`}>
      <p className="text-sm">{message}</p>
    </div>
  );
}
