// web/with-svelte-vite/src/components/ui/ActionPanel.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { cx } from "@/lib/classNames";

  interface Props extends Omit<HTMLAttributes<HTMLElement>, "title"> {
    title: string;
    api?: string;
    description?: string;
    actions?: Snippet;
    hint?: string;
    children?: Snippet;
    className?: string;
  }

  let { title, api, description, actions, hint, children, className, ...sectionProps }: Props = $props();

  const titleId = $props.id();
</script>

<section
  aria-labelledby={titleId}
  class={cx("grid content-start gap-6 px-gutter pt-8 pb-10 md:px-sheet-x", className)}
  {...sectionProps}>
  <header class="grid gap-2">
    <h2 id={titleId} class="text-heading tracking-snug md:text-title">{title}</h2>
    {#if api}
      <code class="font-mono text-code break-words text-muted">{api}</code>
    {/if}
  </header>
  {#if description}
    <p class="max-w-[56ch] text-caption text-muted">{description}</p>
  {/if}
  {#if children}
    <div class="grid max-w-field gap-5">{@render children()}</div>
  {/if}
  {#if actions || hint}
    <div class="flex flex-wrap items-center gap-4 pt-2">
      {@render actions?.()}
      {#if hint}
        <p class="text-caption text-muted">{hint}</p>
      {/if}
    </div>
  {/if}
</section>

// web/with-chrome-extension/src/components/ui/ActionPanel.tsx
import { useId, type ComponentPropsWithoutRef, type ReactNode } from "react";
import { cx } from "@/lib/classNames";

interface ActionPanelProps extends Omit<ComponentPropsWithoutRef<"section">, "title"> {
  title: string;
  api?: string;
  description?: ReactNode;
  actions?: ReactNode;
  hint?: ReactNode;
}

export function ActionPanel({ title, api, description, actions, hint, children, className, ...sectionProps }: ActionPanelProps) {
  const titleId = useId();

  return (
    <section
      aria-labelledby={titleId}
      className={cx("grid content-start gap-6 px-gutter pt-8 pb-10 md:px-sheet-x", className)}
      {...sectionProps}>
      <header className="grid gap-2">
        <h2 id={titleId} className="text-heading tracking-snug md:text-title">
          {title}
        </h2>
        {api && <code className="font-mono text-code break-words text-muted">{api}</code>}
      </header>
      {description && <p className="max-w-[56ch] text-caption text-muted">{description}</p>}
      {children && <div className="grid max-w-field gap-5">{children}</div>}
      {(actions || hint) && (
        <div className="flex flex-wrap items-center gap-4 pt-2">
          {actions}
          {hint && <p className="text-caption text-muted">{hint}</p>}
        </div>
      )}
    </section>
  );
}
