// examples-hub/web/with-react-nextjs/para-modal-cosmos/src/components/ui/SignatureDisplay.tsx
interface SignatureDisplayProps {
  signature: string;
}

export function SignatureDisplay({ signature }: SignatureDisplayProps) {
  if (!signature) return null;

  return (
    <div className="bg-white rounded-none border border-gray-200 p-6">
      <h3 className="text-lg font-medium mb-2">Signature</h3>
      <div className="bg-gray-50 p-4 rounded-none border border-gray-200 break-all" data-testid="sign-signature-display">
        <code className="text-sm text-gray-800 font-mono">{signature}</code>
      </div>
    </div>
  );
}

// web/with-svelte-vite/src/components/ui/SignatureDisplay.svelte
<script lang="ts">
  export let signature: string = "";
</script>

<div class="mt-6 rounded-none border border-gray-200">
  <div class="px-6 py-3 bg-gray-50 border-b border-gray-200">
    <h3 class="text-sm font-medium text-gray-900">Signature</h3>
  </div>
  <div class="px-6 py-3">
    <p class="text-sm text-gray-600 font-mono break-all" data-testid="sign-signature-display">
      {signature}
    </p>
  </div>
</div>
