// web/with-react-nextjs/connector-graz/src/components/ui/StatusAlert.tsx
interface StatusAlertProps {
  show: boolean;
  type: "info" | "error" | "success";
  message: string;
}

export function StatusAlert({ show, type, message }: StatusAlertProps) {
  if (!show) return null;

  const styles = {
    info: "bg-blue-50 border-blue-200 text-blue-900",
    error: "bg-red-50 border-red-200 text-red-900",
    success: "bg-green-50 border-green-200 text-green-900",
  };

  return (
    <div className={`mb-8 rounded-none border px-4 py-3 ${styles[type]}`}>
      <p className="text-sm font-medium">{message}</p>
    </div>
  );
}

// web/with-svelte-vite/src/components/ui/StatusAlert.svelte
<script lang="ts">
  export let show: boolean = false;
  export let type: "info" | "error" | "success" = "info";
  export let message: string = "";

  $: alertClasses = {
    info: "bg-blue-50 text-blue-800 border-blue-200",
    error: "bg-red-50 text-red-800 border-red-200",
    success: "bg-green-50 text-green-800 border-green-200",
  }[type];
</script>

{#if show}
  <div class="mb-6 rounded-none border p-4 {alertClasses}">
    <p class="text-sm font-medium">{message}</p>
  </div>
{/if}
