// web/with-react-nextjs/custom-combined-auth/src/components/ui/VerifyIframe.tsx
interface VerifyIframeProps {
  url: string;
  onCancel: () => void;
  statusMessage?: string;
}

export function VerifyIframe({ url, onCancel, statusMessage }: VerifyIframeProps) {
  return (
    <div className="space-y-4">
      <div className="border border-gray-200 overflow-hidden">
        <iframe
          src={url}
          className="w-full h-[400px] border-0"
          allow="publickey-credentials-get *; publickey-credentials-create *"
          title="Para Verification"
        />
      </div>

      {statusMessage && (
        <div className="text-center text-sm text-gray-500">{statusMessage}</div>
      )}

      <button
        onClick={onCancel}
        className="w-full px-4 py-2 border border-gray-300 text-gray-700 hover:bg-gray-50 transition-colors font-medium">
        Cancel
      </button>
    </div>
  );
}

// web/with-svelte-vite/src/components/ui/VerifyIframe.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";

  interface Props {
    verifyUrl: string;
    onComplete: () => void;
    onCancel: () => void;
  }

  let { verifyUrl, onComplete, onCancel }: Props = $props();

  // Para portal base URL for origin validation
  const portalOrigins = [
    "https://app.getpara.com",
    "https://app.beta.getpara.com",
    "https://app.dev.getpara.com",
  ];

  function handleMessage(event: MessageEvent) {
    // Validate origin comes from Para portal
    const isValidOrigin = portalOrigins.some((origin) =>
      event.origin.startsWith(origin)
    );

    if (!isValidOrigin) return;

    // Handle CLOSE_WINDOW message from Para portal
    if (event.data?.type === "CLOSE_WINDOW") {
      if (event.data?.success) {
        onComplete();
      } else {
        onCancel();
      }
    }
  }

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  onDestroy(() => {
    window.removeEventListener("message", handleMessage);
  });
</script>

<div class="space-y-4">
  <div class="flex items-center justify-between">
    <p class="text-sm text-gray-600">Complete verification below</p>
    <button
      type="button"
      onclick={onCancel}
      class="text-sm text-gray-500 hover:text-gray-700"
    >
      Cancel
    </button>
  </div>

  <iframe
    src={verifyUrl}
    title="Para Verification"
    class="w-full h-[400px] border border-gray-200"
    allow="publickey-credentials-get *; publickey-credentials-create *"
  ></iframe>
</div>
