// web/with-vue-vite/src/components/sign-in/CombinedSignInContainer.vue
<script setup lang="ts">
import { computed, reactive } from "vue";
import Alert from "@/components/ui/Alert.vue";
import Button from "@/components/ui/Button.vue";
import Icon from "@/components/ui/Icon.vue";
import OAuthProviderList from "@/components/ui/OAuthProviderList.vue";
import SegmentedControl from "@/components/ui/SegmentedControl.vue";
import SelectField from "@/components/ui/SelectField.vue";
import SignInPanel from "@/components/ui/SignInPanel.vue";
import StatusHint from "@/components/ui/StatusHint.vue";
import TextField from "@/components/ui/TextField.vue";
import VerificationFrame from "@/components/ui/VerificationFrame.vue";
import { useCombinedAuth } from "@/hooks/useCombinedAuth";
import { formatErrorMessage } from "@/lib/format";
import { getVerifyDescription, getVerifyTitle } from "@/lib/signInCopy";
import { AUTH_TABS, COUNTRY_CODES, OAUTH_PROVIDERS } from "@/lib/signInOptions";

defineProps<{ network: string }>();

const auth = reactive(useCombinedAuth());

const errorMessage = computed(() => formatErrorMessage(auth.errorMessage));

const verifyDestination = computed(() =>
  auth.activeTab === "email" ? auth.email.email : `${auth.phone.countryCode} ${auth.phone.phoneNumber}`
);

const isVerifying = computed(
  () => auth.activeTab !== "social" && auth.step === "verify" && Boolean(auth.verifyUrl || auth.passkeyUrl)
);
</script>

<template>
  <SignInPanel
    v-if="isVerifying"
    :title="getVerifyTitle(Boolean(auth.verifyUrl), Boolean(auth.passkeyUrl))"
    :description="getVerifyDescription(verifyDestination, Boolean(auth.verifyUrl), Boolean(auth.passkeyUrl))"
    :network="network">
    <Alert
      v-if="errorMessage"
      variant="destructive"
      title="Sign in failed">
      {{ errorMessage }}
    </Alert>
    <VerificationFrame
      v-if="auth.verifyUrl"
      :url="auth.verifyUrl" />
    <template v-if="auth.passkeyUrl">
      <Button
        size="lg"
        full-width
        @click="auth.openPasskeyWindow">
        <template #icon>
          <Icon
            name="fingerprint-simple"
            class-name="size-icon-md" />
        </template>
        Open Passkey Verification
      </Button>
      <StatusHint>Waiting for the passkey window to finish.</StatusHint>
    </template>
    <Button
      variant="outline"
      size="lg"
      full-width
      @click="auth.cancel">
      Cancel
    </Button>
  </SignInPanel>

  <SignInPanel
    v-else
    description="Use your email, phone number, or a social account."
    :network="network">
    <SegmentedControl
      label="Sign in with"
      :options="AUTH_TABS"
      :value="auth.activeTab"
      :on-change="auth.setActiveTab"
      :disabled="auth.isPending" />
    <Alert
      v-if="errorMessage"
      variant="destructive"
      title="Sign in failed">
      {{ errorMessage }}
    </Alert>

    <form
      v-if="auth.activeTab === 'email'"
      class="grid gap-4"
      @submit.prevent="auth.email.submit">
      <TextField
        v-model="auth.email.email"
        label="Email address"
        type="email"
        autocomplete="email"
        placeholder="you@example.com"
        :disabled="auth.email.isPending"
        required
        data-testid="email-input" />
      <Button
        type="submit"
        size="lg"
        full-width
        :is-loading="auth.email.isPending"
        :disabled="!auth.email.email.trim()"
        data-testid="continue-email-button">
        Continue with Email
      </Button>
    </form>

    <form
      v-else-if="auth.activeTab === 'phone'"
      class="grid gap-4"
      @submit.prevent="auth.phone.submit">
      <SelectField
        v-model="auth.phone.countryCode"
        label="Country"
        :options="COUNTRY_CODES"
        :disabled="auth.phone.isPending" />
      <TextField
        v-model="auth.phone.phoneNumber"
        label="Phone number"
        type="tel"
        autocomplete="tel-national"
        placeholder="123-456-7890"
        :prefix="auth.phone.countryCode"
        :disabled="auth.phone.isPending"
        required
        data-testid="phone-input" />
      <Button
        type="submit"
        size="lg"
        full-width
        :is-loading="auth.phone.isPending"
        :disabled="!auth.phone.phoneNumber.trim()"
        data-testid="continue-phone-button">
        Continue with Phone
      </Button>
    </form>

    <template v-else>
      <OAuthProviderList
        :providers="OAUTH_PROVIDERS"
        :on-select="auth.oauth.authenticate"
        :active-id="auth.oauth.activeProvider"
        :disabled="auth.oauth.isPending"
        layout="grid"
        label-prefix="" />
      <Alert
        v-if="auth.oauth.isPending"
        title="Continue in the pop-up">
        Complete authentication in the popup window.
      </Alert>
      <Button
        v-if="auth.oauth.isPending"
        variant="outline"
        size="lg"
        full-width
        @click="auth.oauth.cancel">
        Cancel
      </Button>
    </template>
  </SignInPanel>
</template>

// web/with-svelte-vite/src/components/sign-in/CombinedSignInContainer.svelte
<script lang="ts">
  import Alert from "@/components/ui/Alert.svelte";
  import Button from "@/components/ui/Button.svelte";
  import Icon from "@/components/ui/Icon.svelte";
  import OAuthProviderList from "@/components/ui/OAuthProviderList.svelte";
  import SegmentedControl from "@/components/ui/SegmentedControl.svelte";
  import SelectField from "@/components/ui/SelectField.svelte";
  import SignInPanel from "@/components/ui/SignInPanel.svelte";
  import StatusHint from "@/components/ui/StatusHint.svelte";
  import TextField from "@/components/ui/TextField.svelte";
  import VerificationFrame from "@/components/ui/VerificationFrame.svelte";
  import type { CombinedAuth } from "@/hooks/useCombinedAuth.svelte.js";
  import { formatErrorMessage } from "@/lib/format";
  import { SIGN_IN_DESCRIPTION, getVerifyDescription, getVerifyTitle } from "@/lib/signInCopy";
  import { AUTH_TABS, COUNTRY_CODES, OAUTH_PROVIDERS } from "@/lib/signInOptions";

  interface Props {
    auth: CombinedAuth;
    network: string;
  }

  let { auth, network }: Props = $props();

  const email = $derived(auth.email);
  const phone = $derived(auth.phone);
  const oauth = $derived(auth.oauth);
  const errorMessage = $derived(formatErrorMessage(auth.error));
  const destination = $derived(
    auth.activeTab === "email" ? email.email : `${phone.countryCode} ${phone.phoneNumber}`
  );
  const hasFrame = $derived(Boolean(auth.verifyUrl));
  const hasPasskey = $derived(Boolean(auth.passkeyUrl));

  function submitEmail(event: SubmitEvent) {
    event.preventDefault();
    void email.submit();
  }

  function submitPhone(event: SubmitEvent) {
    event.preventDefault();
    void phone.submit();
  }
</script>

{#snippet errorAlert()}
  {#if errorMessage}
    <Alert variant="destructive" title="Sign in failed">{errorMessage}</Alert>
  {/if}
{/snippet}

{#if auth.activeTab !== "social" && auth.step === "verify" && (hasFrame || hasPasskey)}
  <SignInPanel
    title={getVerifyTitle(hasFrame, hasPasskey)}
    description={getVerifyDescription(destination, hasFrame, hasPasskey)}
    {network}>
    {@render errorAlert()}
    {#if auth.verifyUrl}
      <VerificationFrame url={auth.verifyUrl} />
    {/if}
    {#if hasPasskey}
      <Button size="lg" fullWidth onclick={auth.openPasskeyWindow}>
        {#snippet icon()}
          <Icon name="fingerprint-simple" className="size-icon-md" />
        {/snippet}
        Open Passkey Verification
      </Button>
      <StatusHint>Waiting for the passkey window to finish.</StatusHint>
    {/if}
    <Button variant="outline" size="lg" fullWidth onclick={auth.cancel}>Cancel</Button>
  </SignInPanel>
{:else}
  <SignInPanel description={SIGN_IN_DESCRIPTION} {network}>
    <SegmentedControl
      label="Sign in with"
      options={AUTH_TABS}
      value={auth.activeTab}
      onChange={auth.setActiveTab}
      disabled={auth.isPending} />
    {@render errorAlert()}

    {#if auth.activeTab === "email"}
      <form onsubmit={submitEmail} class="grid gap-4">
        <TextField
          label="Email address"
          type="email"
          autocomplete="email"
          placeholder="you@example.com"
          value={email.email}
          oninput={(event) => email.setEmail(event.currentTarget.value)}
          disabled={email.isPending}
          required
          data-testid="email-input" />
        <Button
          type="submit"
          size="lg"
          fullWidth
          isLoading={email.isPending}
          disabled={!email.email.trim()}
          data-testid="continue-email-button">
          Continue with Email
        </Button>
      </form>
    {:else if auth.activeTab === "phone"}
      <form onsubmit={submitPhone} class="grid gap-4">
        <SelectField
          label="Country"
          options={COUNTRY_CODES}
          value={phone.countryCode}
          onchange={(event) => phone.setCountryCode(event.currentTarget.value)}
          disabled={phone.isPending} />
        <TextField
          label="Phone number"
          type="tel"
          autocomplete="tel-national"
          placeholder="123-456-7890"
          prefix={phone.countryCode}
          value={phone.phoneNumber}
          oninput={(event) => phone.setPhoneNumber(event.currentTarget.value)}
          disabled={phone.isPending}
          required
          data-testid="phone-input" />
        <Button
          type="submit"
          size="lg"
          fullWidth
          isLoading={phone.isPending}
          disabled={!phone.phoneNumber.trim()}
          data-testid="continue-phone-button">
          Continue with Phone
        </Button>
      </form>
    {:else}
      <OAuthProviderList
        providers={OAUTH_PROVIDERS}
        onSelect={oauth.authenticate}
        activeId={oauth.activeProvider}
        disabled={oauth.isPending}
        layout="grid"
        labelPrefix="" />
      {#if oauth.isPending}
        <Alert title="Continue in the pop-up">Complete authentication in the popup window.</Alert>
        <Button variant="outline" size="lg" fullWidth onclick={oauth.cancel}>Cancel</Button>
      {/if}
    {/if}
  </SignInPanel>
{/if}
