// web/with-svelte-vite/src/lib/WalletDisplay.svelte
<script lang="ts">
  export let walletAddress: string | undefined;
</script>

<div class="text-center flex flex-col gap-2">
  <h2 class="text-xl font-bold">You are logged in!</h2>
  {#if walletAddress}
    <p>Your first wallet address is: <strong>{walletAddress}</strong></p>
  {:else}
    <p>No wallet found.</p>
  {/if}
</div>

// specialized/with-chrome-extension/src/components/WalletDisplay.tsx
interface WalletDisplayProps {
  walletAddress?: string;
}

export const WalletDisplay = ({ walletAddress }: WalletDisplayProps) => (
  <div className="text-center flex flex-col gap-2">
    <h2 className="text-xl font-bold">You are logged in!</h2>
    {walletAddress ? (
      <p>
        Your first wallet address is: <strong>{walletAddress}</strong>
      </p>
    ) : (
      <p>No wallet found.</p>
    )}
  </div>
);
